name: Delete old workflow runs

on:
    schedule:
        - cron: "12 12 * * *"
    workflow_dispatch:
    push:
        branches:
            - main

concurrency:
    group: delete-runs

jobs:
    delete-old-workflow-runs:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                repository: [ioscdn/laughing-guide, ioscdn/cautious-engine, ioscdn/sync-work-binary]
        steps:
            - name: Delete workflow runs
              uses: Mattraks/delete-workflow-runs@v2
              with:
                  token: ${{ secrets.TOKEN }}
                  repository: ${{ matrix.repository }}
                  retain_days: 7
                  keep_minimum_runs: 10
